# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=255, verbose_name='AGE of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='FIO of User'),
        ),
    ]
